### ISSUE TITLE
Indentation override issue with default

### ISSUE THREAD

**Issue by woodyrew** [atom/language-sass#167] opened 2016-08-22 21:03 UTC
My global indentation is set to 4 soft tabs however when I try to set the `Tab Length` for **SCSS** (and I assume **Sass**) to `2`, the input is replaced with `4`.
If I empty the input it displays a grey placeholder of `Default: 2` - This what I want it to be but tabbing and auto-indentation within `SCSS` files continues to use 4 spaces.

If I set `Tab Length` to `1` or `3` it honours my choice, tabbing and auto-indentation works as expected.

**Comment by 50Wliu** [comment] 2016-08-23 01:21
This is a duplicate of atom/settings-view#774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-23 01:21 UTC

**Comment by woodyrew** [comment] 2016-08-23 14:30
Sorry for the duplication; I didn't find that issue.
