### ISSUE TITLE
Autocomplete issue with punctuation

### ISSUE THREAD

**Issue by kokuou** [atom/language-sass#57] opened 2015-04-25 04:16 UTC
I'm not sure if this is an autocomplete-plus issue or a language-sass issue, but I'm getting suggestions popping up after hitting characters like comma, semicolon, and space. If I try to hit enter quickly after, say, a semicolon, doing so adds "align-content:" (I suppose matching from the top of the suggestions list) instead of breaking to a new line.

![scss-autocomplete](https://cloud.githubusercontent.com/assets/11563926/7331519/09d11144-eac7-11e4-9355-3539d15db458.png)

**Comment by kevinsawicki** [comment] 2015-07-31 16:38
I believe this is a duplicate of https://github.com/atom/autocomplete-plus/issues/513 which has been resolved and released in Atom 1.0.3.

If there are still any issues please open them on the https://github.com/atom/autocomplete-css repository.

**Closed by kevinsawicki** 2015-07-31 16:38 UTC
