### ISSUE TITLE
SCSS Not Properly Highlighting  font-feature-settings property

### ISSUE THREAD

**Issue by aeschli** [atom/language-sass#201] opened 2017-02-23 06:56 UTC
_From @mattbierner on February 22, 2017 7:17_

In a scss file:

```scss
body {
    font-feature-settings: "kern" 1;
    font-kerning: normal;
}
```

Both `font-feature-settings` and `font-kerning` are split into two sections instead of being a single property:

![screen shot 2017-02-21 at 11 13 10 pm](https://cloud.githubusercontent.com/assets/212305/23200834/65d5cc4a-f88b-11e6-88cf-ed5374a85ffc.png)

![screen shot 2017-02-21 at 11 15 23 pm](https://cloud.githubusercontent.com/assets/212305/23200893/c146d3e4-f88b-11e6-8e85-f62d2461ce7e.png)
![screen shot 2017-02-21 at 11 15 30 pm](https://cloud.githubusercontent.com/assets/212305/23200894/c16b5d72-f88b-11e6-8c5d-f23a3eab0db6.png)

_Copied from original issue: Microsoft/vscode#21050_

**Comment by 50Wliu** [comment] 2017-02-23 14:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #161. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-23 14:22 UTC
