### ISSUE TITLE
Sass/Scss variable syntax

### ISSUE THREAD

**Issue by aeschli** [atom/language-sass#188] opened 2016-11-24 09:07 UTC
_From @TheColorRed on November 11, 2016 17:46_

- VSCode Version: 1.7.1
- OS Version: Windows 10

When I create a css variable in scss, I get the following syntax issue:

![scss](https://cloud.githubusercontent.com/assets/1571806/20224471/360eb7e2-a804-11e6-8c01-6698e5eeea87.PNG)

When I convert the file to css, the syntax is correct:

![css](https://cloud.githubusercontent.com/assets/1571806/20224472/361376ba-a804-11e6-8b10-c7435cc9c095.PNG)

_Copied from original issue: Microsoft/vscode#15368_

**Comment by 50Wliu** [comment] 2016-11-24 23:31
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #168. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-11-24 23:31 UTC
