### ISSUE TITLE
Auto indent isn't working 

### ISSUE THREAD

**Issue by johnburkhard** [atom/language-sass#95] opened 2015-12-13 06:30 UTC
When working with SASS files and pressing enter, the auto indent feature isn't working. Tested on a clean install, no plugins or modifications.

**Comment by lee-dohm** [comment] 2015-12-13 18:45
Please be a bit more specific. See the [How Do I Write a (Good) Bug Report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) section of the CONTRIBUTING guide for suggestions.

**Comment by johnburkhard** [comment] 2015-12-13 18:55
When you press enter it doesn't indent.

John Burkhard
724-771-3932
www.johnburkhard.com

**Comment by serhiicss** [comment] 2015-12-18 18:59
This appears to be a feature, not a bug. Some code editors support this and some don't. 

However, once you manually indent the first line, the next one will auto indent.

**Comment by johnburkhard** [comment] 2015-12-18 19:16
It's not a feature, others have complained about it. If the file is .scss and you use curly braces it will auto indent. If the file is .sass and you don't use curly braces it doesn't indent.

**Comment by serhiicss** [comment] 2015-12-19 17:22
I did complain about it myself. Then I tried it in other code editors and as I have mentioned before some support it and some don't. So I figured it must a be a feature. Glad to see it is labeled bug now.

**Comment by lee-dohm** [comment] 2015-12-19 18:42
Even though I do consider this a bug, I'm not sure it will be fixed any time soon. Given what I understand of the Sass syntax, determining when to indent and when not to could be very hard.

Perhaps since the two of you are more familiar with the use of the Sass syntax, you could give some examples of lines where the next line should and shouldn't be indented deeper?

**Comment by johnburkhard** [comment] 2015-12-22 03:14
For starters any classes (.this-class), media queries (@media), selectors (a, img, h1), &:before &:after etc. Those should auto-indent on enter every time. It works in any other editor I've used and I would hate to go back to S3.

**Closed** 2016-06-08 21:04 UTC
Labels: auto-indent, bug
