### ISSUE TITLE
Color for selector is different in css vs scss file

### ISSUE THREAD

**Issue by aeschli** [atom/language-sass#215] opened 2017-06-07 09:24 UTC
_From @ramya-rao-a on June 6, 2017 22:39_

- VSCode Version: 1.12.2 

![screen shot 2017-06-06 at 3 34 27 pm](https://user-images.githubusercontent.com/16890566/26855097-1294818a-4ace-11e7-9131-1541281128df.png)

Doesn't repro in the below themes
- Abyss
- Monokai
- Monokai Dimmed
- Red
- Solarized Dark and light
- Tomorrow Night below

_Copied from original issue: Microsoft/vscode#28154_

**Comment by aeschli** [comment] 2017-06-07 09:24
css uses 'meta.selector', while scss doesn't emit a scope.

**Comment by 50Wliu** [comment] 2017-06-08 03:31
```scss
boo {
	margin: 20px;
	padding: 20px;
}

.hoo {
	margin: 20px;
	padding: 20px;
}
```

**Comment by 50Wliu** [comment] 2017-06-08 03:31
Duplicate of #29.

**Closed by 50Wliu** 2017-06-08 03:31 UTC
